# Generated by Django 5.2.7 on 2025-10-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ocrdocument_corrected_label_studio_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='processing_log',
            field=models.TextField(blank=True, default='', verbose_name='处理日志'),
        ),
    ]
