# Generated by Django 5.2.7 on 2025-10-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ocrdocument_processing_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='label_studio_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='推送时间'),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='label_studio_synced',
            field=models.BooleanField(default=False, verbose_name='已推送到Label Studio'),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='label_studio_task_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Label Studio任务ID列表'),
        ),
    ]
